---
title: "Assignment E: Tidying and Transforming Data in R"
format: 
  html:
    embed-resources: true
editor: visual
---

## Assignment E: Tidying and Transforming Data in R

```{r, echo=FALSE}
#| label: packages
#| warning: false
#| message: false

library(tidyverse)
library(magrittr)

```

## Part 1: World Development Bank Data Dataset (WDBD.csv)

First, let's read in the data and separate the bottom information part from the data itself.
```{r}
#| label: read bank data
#| warning: false
#| message: false

bank_data_raw <- read.csv("WDBD.csv")
bank_data <- bank_data_raw

bank_data_info <- bank_data_raw %>% 
  slice(2982:3079)

```


Let's tidy the information data frame. 

```{r}

headers1 <- as.character(bank_data_info[1, ])
headers2 <- as.character(bank_data_info[2,1:7])
new_headers <- c(headers1, headers2, c("n1", "n2", "n3", "n4"))

bank_data_info <- bank_data_info[-(1:2), ]

empty_matrix <- matrix(vector(), nrow = 48, ncol = 22)
bank_info_clean <- data.frame(empty_matrix)
colnames(bank_info_clean) <- new_headers

j <- 1

for (i in seq(1, 95, by = 2)) {
  part1 <- as.character(bank_data_info[i, ])
  part2 <- as.character(bank_data_info[i+1, ])
  comb_rows <- c(part1, part2)
  
  bank_info_clean[j, ] <- comb_rows
  j <- j+1
}

```

Still tidying the information data frame. 

```{r}
bank_info_clean <- bank_info_clean %>% 
  select(-n2, -n3, -n4) %>% 
  mutate(across(everything(), ~na_if(., ""))) %>% 
  mutate(`License URL` = coalesce(`License URL`, n1)) %>% 
  select(-n1)
```



Now let's tidy the actal data. 

```{r}
#| label: tidying bank data
# AI helped with some of this code 

bank_data <- bank_data %>% 
  slice(-(2977:3079)) %>%
  rename_with(
    ~str_extract(.x, "\\d{4}"),
    .cols = starts_with("X")
  ) %>% 
  rename_with(
    ~gsub("\\.", " ", .x), # The replacement pattern
    .cols = 1:4           # The columns to apply the change to
  ) %>% 
  mutate(across(everything(), ~na_if(., ".."))) %>% 
  pivot_longer(
    cols = c(`2018`:`2024`), 
    names_to = "Year", 
    values_to = "Value" 
  )

```
